#!/bin/sh

ifs_=$IFS

#right=''
#arrow=' '
#play=''
gt=''
play=$gt

setpath()
{
	case $PATH in
	*$1*) ;;
	*) export PATH=$PATH:$1;;
	esac
}

branch_=''
branch() { eval branch_=\$$#; }
gitps()
{
	branch_=''
	if [ ! -d .git -o ! -f .git/HEAD ]; then
		printf " "
		return
	fi

	while read line; do
		IFS='/'; branch $line; IFS=$ifs_
	done < .git/HEAD

	if [ -z "$branch_" ]; then
		printf " "
	else
#		if [ "$TERM" = "linux" ]; then
#			printf ":\033[1;36m$branch_\033[0m"
		if [ $# -eq 1 ]; then
			printf "[$branch_] "
		else
			printf " $branch_ "
		fi
	fi
}

devps()
{
	if [ -z "$ANDROID_SERIAL" ]; then
		return
	fi
	if [ "$TERM" = "linux" ]; then
		printf "$ANDROID_SERIAL "
	else
		printf "  $ANDROID_SERIAL "
	fi
}

xtermps()
{
	path_color="\[\e[0m\]\[\e[1;94m\]"
	git_color="\[\e[0m\]\[\e[0;95m\]"
	line0='$host_color\H $play $user_color\u ${play_color}$play'
	line1='$path_color \w${git_color}$(gitps)${path_color}$gt \[\e[0m\]'
	title='\[\e]0;\]$(gitps 1)\w\a'
	PS1="$line0$line1$title"
}

setpath $HOME/bin

export EDITOR=vim

[ -z "$PS1" ] && return # If not running interactively, don't do anything

alias ls='ls --color'
alias grep='grep --color'

if [ "$USER" = "root" ]; then
	user_color="\[\e[0m\]\[\e[1;93m\]"
	play_color="\[\e[0m\]\[\e[0;93m\]"
	host_color="\[\e[0m\]\[\e[1;90m\]"
else
	user_color="\[\e[0m\]\[\e[1;94m\]"
	play_color="\[\e[0m\]\[\e[1;94m\]"
	host_color="\[\e[0m\]\[\e[1;90m\]"
fi

if [ "$TERM" = "linux" ]; then
#	PS1='\H@\u \w$(gitps) > '
	gt='>'
fi

xtermps
