#!/bin/sh

_parse_param() {
	mount $2 /system
}

_parse_cmdline() {
	while [ $# -gt 1 ]; do
		case $1 in
		system=*) export IFS='='; _parse_param $1; exit 0;;
		esac
		shift
	done
}

mkdir -p /system
_parse_cmdline $(cat /proc/cmdline)
