#!/bin/sh
#
# Copyright (C) 2015, Aliaksei Katovich <aliaksei.katovich at gmail.com>
#
# Released under the GNU General Public License, version 2

_tmp=/tmp/$USER
_ipc=$_tmp/irssi-notify.ipc
_app=$(basename $0)
_scr=/tmp/$USER/irssi-notify-loop
_pid=$$

_grep()
{
	ps ax |
	grep -E "$@" |
	grep -v grep |
	grep -v vim |
	sed 's/^[[:blank:]]\+//' |
	grep -vE "^$_pid" |
	cut -f1 -d' '
}

_stop()
{
	_grep $1 | while read pid; do
		kill $pid
	done
}

_cpid()
{
	ps ax | grep -E "urxvt.*$1" | grep -v grep | \
	sed 's/^[[:blank:]]\+//' | cut -f1 -d' '
}

_pwid()
{
	local wid=$(wmctrl -p -l | grep $1 | cut -f1 -d' ')

	if [ -z "$wid" ]; then
		pid=$(_cpid $1)
		if [ -z "$pid" ]; then
			echo ""
			return
		fi
		wid=$(wmctrl -p -l | grep $pid | cut -f1 -d' ')
		if [ -z "$wid" ]; then
			echo ""
			return
		fi
		touch ~/.irssi/pids/$pid
	fi
	echo "$wid"
}

_icon()
{
	local wid=$(_pwid $1)

	if [ -z "$wid" ]; then
		return
	fi
	xdotool set_window --classname URxvt --class $2 $wid 2>/dev/null
}

_recv()
{
	killall -9 play >/dev/null 2>&1
#	exec play -q /usr/share/sounds/purple/receive.wav &
	sudo /opt/bin/laptop-led 0 blink
	_icon $1 face-smile
}

_send()
{
	killall -9 play >/dev/null 2>&1
#	exec play -q /usr/share/sounds/purple/send.wav &
	sudo /opt/bin/laptop-led 0 off
	irssi-notify-show $1
	_icon $1 user-invisible
}

if [ -n "$1" -a -n "$2" ]; then
	if [ "$1" = "$2" ]; then
		_send $3
		exit 0
	fi
fi

_recv $3
mkdir -p $_tmp
mkfifo $_ipc 2>/dev/null
_stop $_scr >/dev/null 2>&1

if [ -f $HOME/.icons/irssi-message.png ]; then
	_ico1=$HOME/.icons/irssi-message.png
else
	_ico1=face-smile
fi

if [ -f $HOME/.icons/irssi-typing.png ]; then
	_ico2=$HOME/.icons/irssi-typing.png
else
	_ico2=user-invisible
fi

(
	echo "#!/bin/sh"
	echo "i=0"
	echo "while :; do"
	echo "  if [ \$i -eq 0 ]; then"
	echo "    echo \"icon:$_ico1\" > $_ipc"
	echo "    i=1"
	echo "  else"
	echo "    echo \"icon:$_ico2\" > $_ipc"
	echo "    i=0"
	echo "  fi"
	echo "  if [ \$? -ne 0 ]; then"
	echo "    break"
	echo "  fi"
	echo "sleep 1"
	echo "done"
) > $_scr 2>/dev/null
chmod +x $_scr
exec $_scr >/dev/null >/dev/null 2>&1 &
_stop $_app >/dev/null 2>&1
