#!/bin/sh
#
# Copyright (C) 2015, Aliaksei Katovich <aliaksei.katovich at gmail.com>
#
# Released under the GNU General Public License, version 2

_tmp=/tmp/$USER
_ipc=$_tmp/irssi-notify.ipc

_grep()
{
	ps ax |
	grep -E "$@" |
	grep -v grep |
	grep -v vim |
	sed 's/^[[:blank:]]\+//' |
	cut -f1 -d' '
}

_kill()
{
	kill $@ >/dev/null 2>&1
}

_icon()
{
	xdotool set_window --classname URxvt --class user-invisible $1
}

if [ -n "$1" ]; then
	pid=$(wmctrl -l -p | grep "$1" | sed 's/[[:blank:]]\+/ /g;' | cut -f3 -d' ')
	if [ ! -d /proc/$pid ]; then
		rm -f ~/.irssi/pids/$pid
	else
		if [ -f ~/.irssi/pids/$pid ]; then
			_icon $1
		fi
	fi
fi

mkdir -p $_tmp
mkfifo $_ipc 2>/dev/null

_grep irssi-notify-msg | while read pid; do
	_kill $pid
done

_grep irssi-notify-loop | while read pid; do
	_kill $pid
done

if [ -f $HOME/.icons/irssi-online.png ]; then
	_ico=$HOME/.icons/irssi-online.png
else
	_ico=user-online
fi

echo "icon:$_ico" > $_ipc
sudo /opt/bin/laptop-led 0 on
