#!/bin/sh
#
# Copyright (C) 2015, Aliaksei Katovich <aliaksei.katovich at gmail.com>
#
# Released under the GNU General Public License, version 2

tmp=/tmp/$USER/$(basename $0)
win=$(xdotool getactivewindow)
args=''

getcolor_()
{
	xrdb -query | grep -E "^\*$1:" | sed 's/[[:blank:]]\+/ /' | cut -f2 -d' '
}

normal_()
{
	args="--fg=$(getcolor_ foreground) --bg=$(getcolor_ background)"
	for i in $(seq 0 15); do
		args="$args --color$i=$(getcolor_ color$i)"
	done
}

inverted_()
{
	# auto does not look always good so customize
	# args="--fg=$(getcolor_ background) --bg=$(getcolor_ foreground)"
	args="--fg=$(getcolor_ color0) --bg=$(getcolor_ color7)"

	# black
	color=$(getcolor_ color8)
	args="$args --color0=$(getcolor_ color7)"
	args="$args --color8=$(getcolor_ color15)"

	# red
	args="$args --color1=$(getcolor_ color9)"
	args="$args --color9=$(getcolor_ color1)"

	# green
	args="$args --color2=$(getcolor_ color10)"
	args="$args --color10=$(getcolor_ color2)"

	# yellow
	args="$args --color3=$(getcolor_ color11)"
	args="$args --color11=$(getcolor_ color3)"

	# blue
	args="$args --color4=$(getcolor_ color12)"
	args="$args --color12=$(getcolor_ color4)"

	# magenta
	args="$args --color5=$(getcolor_ color13)"
	args="$args --color13=$(getcolor_ color5)"

	# cyan
	args="$args --color6=$(getcolor_ color14)"
	args="$args --color14=$(getcolor_ color6)"

	# white
	args="$args --color7=$(getcolor_ color0)"
	args="$args --color15=$(getcolor_ color8)"
}

mkdir -p $tmp

if [ ! -s $tmp/$win ]; then
	echo 0 > $tmp/$win
fi

while read n; do
	export TERM=xterm
	if [ -n "$n" -a $n -eq 0 ]; then
		inverted_
		echo 1 > $tmp/$win
	else
		normal_
		echo 0 > $tmp/$win
	fi
	xtermcontrol -f $args
done < $tmp/$win
