#!/bin/sh
#
# Copyright (C) 2015, Aliaksei Katovich <aliaksei.katovich at gmail.com>
#
# Released under the GNU General Public License, version 2

setmax() { max=$2; }
setvol() { vol=$2; }

strip() { echo $1; }

parseinfo()
{
	while [ $# -ne 0 ]; do
		str=$(strip $1)
		case $str in
		*max=*) IFS='='; setmax $str; IFS=$ifs;;
		*values=*) IFS='='; setvol $str; IFS=$ifs;;
		esac
		shift 1
	done
}

cmd=$1
ifs=$IFS
cid=$(amixer controls | grep -iE "master.*playback.*volume")
inf=$(echo $(amixer cget "$cid" | sed 's/^.*[,]max=/;max=/;s/[:,]/;/g'))
max=0
vol=0
IFS=';'; parseinfo $inf; IFS=$ifs
step=$((max / 10))

if [ "$cmd" = "inc" ]; then
	new=$((vol + step))
elif [ "$cmd" = "dec" ]; then
	new=$((vol - step))
elif [ "$cmd" = "cur" ]; then
	new=$vol
elif [ "$cmd" = "off" ]; then
	new=0
else
	new=$vol
fi

if [ $new -lt 0 ]; then
	new=0
elif [ $new -ge $max ]; then
	new=$max
fi

amixer cset "$cid" $new,$new >/dev/null
vol=$(amixer sget Master | grep -E "\%" | cut -f1 -d'%' | cut -f2 -d'[')
xsetroot -name "mixer $vol"
