#!/bin/sh
#
# Copyright (C) 2015, Aliaksei Katovich <aliaksei.katovich at gmail.com>
#
# Released under the GNU General Public License, version 2

app=$(basename $0)
cmd=$(echo $app | cut -f2 -d'-')
dir=$1
msk=''

case "$1" in
--install)
	if [ -z "$2" ]; then
		echo "Usage: $app --install <dir>"
		exit 1
	fi
	ln -sf $0 $2/$app
	for sufx in asm kconfig makefile headers cpp hpp py; do
		ln -sf $0 $2/$app-$sufx
	done
	exit 0
	;;
esac

shift

if [ -z "$dir" -o -z "$1" ]; then
	echo "Usage: $app <dir> <exp>"
	echo "       $app --install <dir>"
	exit 0
fi

case "$cmd" in
asm) expr='^.*[.]asm$';;
kconfig) expr='Kconfig$';;
makefile) expr='^.*akefile.*\|^.*[.]mk$';;
headers) expr='^.*h$\|^.*hpp$';;
cpp) expr='^.*[.]cpp$';;
hpp) expr='^.*[.]hpp$';;
py) expr='^.*[.]py$';;
*) expr='^.*[.]c$\|^.*[.]h$\|^.*[.]C$\^.*[.]H$\|^.*[.]cpp$\|^.*[.]hpp$';;
esac

set -x
find -L $dir -regex ${expr} | xargs grep --color -HnE "$@"
