#!/bin/sh

_parse_bits() {
	if [ $2 -eq 8 ]; then
		echo "-8"
	fi
}

_parse_speed() {
	echo $1
}

_parse_value() {
	local speed=$(export IFS='n'; _parse_speed $2)
	local bits=$(export IFS='n'; _parse_bits $2)
	exec /sbin/getty $bits $speed $1
}

_parse_param() {
	export IFS=','
	_parse_value $2
}

_parse_cmdline() {
	while [ $# -gt 1 ]; do
		case $1 in
		console=*) export IFS='='; _parse_param $1; exit 0;;
		esac
		shift
	done
}

_parse_cmdline $(cat /proc/cmdline)
